import { Metadata } from 'next';
import React, { Suspense } from 'react'
import AllPosts from '../_components/AllPosts/AllPosts';
import UpdatePhoto from '../_components/UpdatePhoto/UpdatePhoto';
import CreatePostForm from '../_components/CreatePostForm/CreatePostForm';
import { Container, Stack } from '@mui/material';
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const page = () => {
  return (
    <Container>
      <Stack spacing={2} sx={{width:{md:'65%',xs:'95%'}, margin:'auto', marginBlock:4}}>
        <UpdatePhoto/>
        <CreatePostForm/>
        <Suspense fallback={<div>Loading...</div>}>
        <AllPosts/>
        </Suspense>
      </Stack>
    </Container>
  )
}

export default page
